export const products: any[] = [
  {
    name: "Next.js Course",
    description: "Learn Next.js and build a complete application",
    price: 29.99,
    ratings: 4.5,
    discount: 0,
    featuredImage: "https://i.imgur.com/yD1beHb.jpg",
    category: "Web Development",
    company: "y17godara",
    addedBy: "y17godara",
  },
  {
    name: "React.js Course",
    description: "Learn React.js and build a complete application",
    price: 29.99,
    ratings: 4.0,
    discount: 30,
    featuredImage: "https://i.imgur.com/6B0Wbtr.png",
    category: "Web Development",
    company: "y17godara",
    addedBy: "y17godara",
  },
  {
    name: "Node.js Course",
    description: "Learn Node.js and build a Discord Bot",
    price: 29.99,
    ratings: 4.5,
    discount: 50,
    featuredImage: "https://i.imgur.com/6B0Wbtr.png",
    category: "Backend Development",
    company: "y17godara",
    addedBy: "y17godara",
  },
];
